name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: | 
            node_modules 
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@master
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_05AC71003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "dist/static" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          PRE_BUILD_COMMAND: './scripts/setup-puppeteer.sh'
      - name: run lighthouse
        env:
            CI: true
            API_KEY: ${{ secrets.PSI_KEY }}
        run: |
          mkdir -p output/statistics/
          ls -al
          [[ -d node_modules ]] || npm install
          npm run psi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: psi-data
          path: |
            output/statistics/
            !output/statistics/raw_*.json
      - name: Archive PSI report results
        uses: actions/upload-artifact@v2
        with:
          name: psi-report
          path: output/statistics/index.html

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@master
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_05AC71003 }}
          action: "close"
