name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: | 
            node_modules 
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Create .env file
        env:
          GH_SERVER_URL: ${{ github.server_url }}
        run: |
          touch .env
          echo "write env to script: $GITHUB_RUN_ID"
          echo GITHUB_RUN_NUMBER=${{ github.run_number }} >> .env
          echo TEST_VAR="$GH_SERVER_URL" >> .env
          echo TEST_VAR2="$GH_SERVER_URL/$GH_SERVER_URL" >> .env
          echo GITHUB_SERVER_URL=${{ github.server_url }} >> .env
          echo GITHUB_REPOSITORY=${{ github.repository }} >> .env
          echo GITHUB_RUN_ID=${{ github.run_id }} >> .env
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@master
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_05AC71003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist/static" # Built app content directory - optional
          # app_artifact_location: "dist/static" # Built app content directory - optional (deprecated it seems)
          ###### End of Repository/Build Configurations ######
        env:
          PRE_BUILD_COMMAND: './scripts/setup-puppeteer.sh'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@master
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_05AC71003 }}
          action: "close"
