name: IONOS.space

on: [push]
env:
  PSI_KEY: ${{ secrets.PSI_KEY }}
  IS_FORK: ${{ secrets.IS_FORK }}
jobs:
  ionos-space:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'willi84' )}}
    steps:
      - name: Get Ionos Project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          project: 132fc3eb-f436-40f4-8008-58f30fde5918
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/cache@v2
        with:
          path: | 
            node_modules 
            output 
            docs 
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Setup Node.js 12.16.x
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm install
      - name: Build Node project
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm run build
        env:
          CI: true
          SITE_URL: ${{ steps.project.outputs.site-url }}
      - name: Deploy to IONOS
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: dist/static
          project: 132fc3eb-f436-40f4-8008-58f30fde5918
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          branch-id: ${{ steps.project.outputs.branch-id }}
      - name: run lighthouse
        env:
          CI: true
          PSI_KEY: ${{ secrets.PSI_KEY }}
        run: |
          mkdir -p docs/
          ls -al
          [[ -d node_modules ]] || npm install
          npm run psi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: psi-data
          path: |
            docs/
            !docs/raw_*.json
      - name: Archive PSI report results
        uses: actions/upload-artifact@v2
        with:
          name: psi-report
          path: output/statistics/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          clean: false
          single-commit: true