name: Node CI

on:
  repository_dispatch:
    types: [psi-event]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          mkdir -p output/statistics/
          npm install
          npm run psi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: psi-data
          path: |
            output/statistics/
            !output/statistics/raw_*.json
      - name: Archive PSI report results
        uses: actions/upload-artifact@v2
        with:
          name: psi-report
          path: output/statistics/index.html